const KEY_UP_FIRST = 38;
const KEY_UP_SECOND = 87;
const KEY_DOWN_FIRST = 40;
const KEY_DOWN_SECOND = 83;
const KEY_RIGHT_FIRST = 39;
const KEY_RIGHT_SECOND = 68;
const KEY_LEFT_FIRST = 37;
const KEY_LEFT_SECOND = 65;
