const Config = {
	COUNT_OF_CELLS_WIDTH: 23,
	COUNT_OF_CELLS_HEIGHT: 17,
	CELL_SIZE: 30,
	FIELD_COLOR: 'green',
	SCORE_BONUS: 100,
	PLAYER_SPEED: 2,
	MONSTER_BALLOON_SPEED: 0.7,
	MONSTER_DROP_SPEED: 0.5,
	RESOURCES_TO_LOAD_COUNT: 79,
	PLAYER_SIZE: 26,
	PLAYER_STEP_DURATION: 150,
	MONSTER_SIZE: 30,
	MONSTER_STEP_DURATION: 200,
	START_POS_PLAYER: 30,
	START_LIVE: 2,
	START_BOMB_COUNT: 3,
	BOMB_TIMER: 4000,
	EXPLODING_TIME: 200,
	BOMB_SIZE: 30
};

Config.WIDTH = Config.CELL_SIZE * Config.COUNT_OF_CELLS_WIDTH;
Config.HEIGHT = Config.CELL_SIZE * Config.COUNT_OF_CELLS_HEIGHT;