Config = {
	COUNT_OF_CELLS_WIDTH: 16,
	COUNT_OF_CELLS_HEIGHT: 13,
	WIDTH: 480,
	HEIGHT: 390,
	CELL_SIZE: 30,
	PLAYER_SPEED: 2,
	MONSTER_SPEED: 0.7,
	resourcesToLoadCount: (27 + 28 + 1),
	PLAYER_SIZE: 26,
	MONSTER_SIZE: 30,
	START_POS_PLAYER: 30,
	START_LIVE: 2,
	START_BOMB_COUNT: 3,
	BOMB_TIMER: 4000,
	EXPLODING_TIME: (50 * 4),
	BOMB_SIZE: 30
};
//field = getField(LEVEL_1);