const Config = {
	COUNT_OF_CELLS_WIDTH: LEVEL_1[0].length,
	COUNT_OF_CELLS_HEIGHT: LEVEL_1.length,
	CELL_SIZE: 30,
	PLAYER_SPEED: 2,
	MONSTER_BALLOON_SPEED: 0.7,
	MONSTER_DROP_SPEED: 0.5,
	RESOURCES_TO_LOAD_COUNT: 77,
	PLAYER_SIZE: 26,
	MONSTER_SIZE: 30,
	START_POS_PLAYER: 30,
	START_LIVE: 2,
	START_BOMB_COUNT: 3,
	BOMB_TIMER: 4000,
	EXPLODING_TIME: 200,
	BOMB_SIZE: 30
};

Config.WIDTH = Config.CELL_SIZE * Config.COUNT_OF_CELLS_WIDTH;
Config.HEIGHT = Config.CELL_SIZE * Config.COUNT_OF_CELLS_HEIGHT;